[Profile]
name = BlueBEAR

[QOS]
options = bbdefault, bbshort, bbgpu

[Constraints]
options = :No constraint, emerald:Emerald (Intel Xeon Platinum 8570), sapphire:Sapphire Rapids (Intel Xeon Platinum 8480CL), icelake:Ice Lakes (Intel Xeon Platinum 8360Y)

[Preamble]
line1 = module purge
line2 = module load bluebear